name: Build APK

on:
  push:
    branches:
      - '*'
    
jobs:
  check:
    name: Check whether to build or not
    runs-on: ubuntu-latest
    outputs:
      buildapk: ${{steps.step1.outputs.buildapk}}
    steps:
      - uses: actions/checkout@v3
      - run: echo "buildapk=$(cat buildapk.txt)" >> $GITHUB_OUTPUT
  build:
    name: Building Debug APK
    needs: check
    if: needs.check.outputs.buildapk == '1' || needs.check.outputs.buildapk == '2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Flutter Setup
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - run: |
          if ${{ needs.check.outputs.buildapk }} == '2'
          then
            echo ${{ secrets.HereCreds }} > credentials.env
          fi
        shell: bash
      - run: flutter pub get
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v3
        with:
          name: Navigation Debug APK
          path: build/app/outputs/apk/debug/app-debug.apk
